server:
  port: ${PORT:5000}
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: dgs-playground
  aop:
    proxy-target-class: false
  profiles:
    active: ${SPRING_ACTIVE_PROFILES:dev}
  jmx:
    enabled: false
  sql:
    init:
      platform: postgres
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    hikari:
      auto-commit: false
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0.0
